# Generated by Django 3.0.4 on 2020-03-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200329_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonsballroomdancing',
            options={'verbose_name': 'Уроки по бальным танцам'},
        ),
        migrations.AlterModelOptions(
            name='lessonspreschoolers',
            options={'verbose_name': 'Уроки для дошкольников'},
        ),
        migrations.AlterModelOptions(
            name='lessonsschoolstudents',
            options={'verbose_name': 'Уроки для школьников'},
        ),
    ]
