# Generated by Django 3.0.4 on 2020-06-01 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200329_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('author', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lessonsballroomdancing',
            options={'verbose_name': 'урок по бальным танцам', 'verbose_name_plural': 'Уроки по бальным танцам'},
        ),
        migrations.AlterModelOptions(
            name='lessonspreschoolers',
            options={'verbose_name': 'урок для дошкольников', 'verbose_name_plural': 'Уроки для дошкольников'},
        ),
        migrations.AlterModelOptions(
            name='lessonsschoolstudents',
            options={'verbose_name': 'урок для школьников', 'verbose_name_plural': 'Уроки для школьников'},
        ),
    ]
