# Generated by Django 3.0.4 on 2020-06-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200601_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=250, verbose_name='Категория матодических материалов')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-publish',), 'verbose_name': 'методические материалы', 'verbose_name_plural': 'Методические материалы'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=250, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.ArticlesCategories'),
            preserve_default=False,
        ),
    ]
