# Generated by Django 3.0.4 on 2020-06-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200601_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
