# Generated by Django 3.0.4 on 2020-06-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_articles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
