# Generated by Django 3.0.4 on 2020-06-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.ArticlesCategories'),
        ),
    ]
