# Generated by Django 3.0.4 on 2020-06-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(max_length=250, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='ArticlesCategories',
        ),
    ]
