# Generated by Django 3.0.4 on 2020-06-01 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200601_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescategories',
            options={'verbose_name': 'категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
    ]
