# Generated by Django 3.0.4 on 2020-06-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_articles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
    ]
