# Generated by Django 3.0.4 on 2020-06-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_articles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(default='None', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
