# Generated by Django 3.0.4 on 2020-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_articles_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-updated',), 'verbose_name': 'методические материалы', 'verbose_name_plural': 'Методические материалы'},
        ),
        migrations.RenameField(
            model_name='articlescategories',
            old_name='categories',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='publish',
        ),
        migrations.AddField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(default='', max_length=250, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='updated', verbose_name='Ссылка'),
        ),
    ]
