# Generated by Django 3.0.4 on 2020-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200601_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescategories',
            name='created',
        ),
        migrations.AddField(
            model_name='articlescategories',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='updated', verbose_name='Ссылка'),
        ),
    ]
