# Generated by Django 3.0.4 on 2020-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200601_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
