# Generated by Django 3.0.4 on 2020-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_articles_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('cover', models.ImageField(upload_to='images/', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('body', models.TextField(verbose_name='Основной текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('-updated',),
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(upload_to='images/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='category',
            field=models.CharField(max_length=250, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='articlescategories',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Ссылка'),
        ),
    ]
