# Generated by Django 3.0.4 on 2020-06-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200604_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonsBallroomDancing',
        ),
        migrations.DeleteModel(
            name='LessonsPreschoolers',
        ),
        migrations.DeleteModel(
            name='LessonsSchoolStudents',
        ),
    ]
