# Generated by Django 3.0.4 on 2020-06-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200604_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
