# Generated by Django 3.0.4 on 2020-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200605_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.SlugField(unique=True, verbose_name='Ссылка на альбом из Вк')),
                ('cover', models.ImageField(blank=True, upload_to='images/gallery', verbose_name='Превью (не обязательно)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('draft', 'Скрыто'), ('published', 'Опубликовано')], default='draft', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'альбом галереи',
                'verbose_name_plural': 'Альбомы галереии',
                'ordering': ('-created',),
            },
        ),
    ]
