# Generated by Django 3.0.7 on 2020-06-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20200606_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='album',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Gallery', verbose_name='Альбом (не обязательно)'),
            preserve_default=False,
        ),
    ]
