# Generated by Django 3.0.7 on 2020-06-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_news_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='album',
        ),
    ]
